name       : freeorion
version    : 0.4.8
release    : 15
source     :
    - https://github.com/freeorion/freeorion/releases/download/v0.4.8/FreeOrion_v0.4.8_2018-08-23.26f16b0_Source.tar.gz : d405dbeb43afb7fa76937cf15cdb10b15e818da171ec1eb03e4a1c3ecbba46f7
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-only
component  : games.strategy
summary    : FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game
description: |
    FreeOrion is a free, Open Source, turn-based space empire and galactic conquest computer game.

    FreeOrion is inspired by the tradition of the Master of Orion games, but does not try to be a clone or remake of that series or any other game.  It builds on the classic *4X* (eXplore, eXpand, eXploit and eXterminate) model.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - libboost-devel
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
