name       : freeorion
version    : 0.4.10.2
release    : 31
source     :
    - https://github.com/freeorion/freeorion/releases/download/v0.4.10.2/FreeOrion_v0.4.10.2_2021-08-01.f663dad_Source.tar.gz : f6056ee97edd46dee8076cc1cdb11c711652f1e26f03cec1244a01a3cd5b0d70
homepage   : https://www.freeorion.org
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-only
component  : games.strategy
summary    : FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game
description: |
    FreeOrion is a free, Open Source, turn-based space empire and galactic conquest computer game. It is inspired by the tradition of the Master of Orion games, but does not try to be a clone or remake of that series or any other game.  It builds on the classic *4X* (eXplore, eXpand, eXploit and eXterminate) model.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(python3)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - libboost-devel
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
