name       : freeorion
version    : 0.4.5
release    : 4
source     :
    - https://github.com/freeorion/freeorion/releases/download/v0.4.5/FreeOrion_v0.4.5_2015-09-01.f203162_Source.tar.gz : 3b99b92eeac72bd059566dbabfab54368989ba83f72e769bc94eb8dd4fe414c0
license    :
    - CC BY-SA 3.0 # Artistic and Creative Content
    - GPL-2.0 # Source
component  : games.strategy
summary    : FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game
description: |
    FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(openal)
    - pkgconfig(python-2.7)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=%libdir% .
build      : |
    %make
install    : |
    %make_install
