name       : freeorion
version    : 0.4.7.1
release    : 12
source     :
    - https://github.com/freeorion/freeorion/releases/download/v0.4.7.1/FreeOrion_v0.4.7.1_2017-09-03.139ffd9_Source.tar.gz : 15ace123318e46321b95a358439145ad1835d8edbc020afbf295f4919a0fa131
license    :
    - CC BY-SA 3.0 # Artistic and Creative Content
    - GPL-2.0 # Source
component  : games.strategy
summary    : FreeOrion is a free, open source, turn-based space empire and galactic
    conquest (4X) computer game
description: |
    FreeOrion is a free, Open Source, turn-based space empire and galactic conquest computer game.

    FreeOrion is inspired by the tradition of the Master of Orion games, but does not try to be a clone or remake of that series or any other game.  It builds on the classic *4X* (eXplore, eXpand, eXploit and eXterminate) model.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(openal)
    - pkgconfig(python-2.7)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
