name       : freeorion
version    : 0.4.5
release    : 1
source     :
    - https://github.com/freeorion/freeorion/archive/v0.4.5.tar.gz : e52f648b718e6f133a02ef8c0ee78090598d69bddf1b9a0842f9c9ed67c17551
license    :
    - CC BY-SA 3.0 # Artistic and Creative Content
    - GPL-2.0 # Source
component  : games.strategy
summary    : FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game
description: |
    FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(openal)
    - pkgconfig(python-2.7)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
