name       : freeorion
version    : 0.4.10.1
release    : 24
source     :
    - https://github.com/freeorion/freeorion/releases/download/v0.4.10.1/FreeOrion_v0.4.10.1_2020-09-25.39cfe10_Source.tar.gz : 0006191adb5046d51116f6e5a657773f2015af7c23684f29e2a7dff7daf5e4e7
homepage   : https://www.freeorion.org
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-only
component  : games.strategy
summary    : FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game
description: |
    FreeOrion is a free, Open Source, turn-based space empire and galactic conquest computer game. It is inspired by the tradition of the Master of Orion games, but does not try to be a clone or remake of that series or any other game.  It builds on the classic *4X* (eXplore, eXpand, eXploit and eXterminate) model.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(python3)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - libboost-devel
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
