name       : freeorion
version    : 0.4.6
release    : 9
source     :
    - http://pilotfiber.dl.sourceforge.net/project/freeorion/FreeOrion/FreeOrion%20Version%200.4.6/FreeOrion_v0.4.6_2016-09-16.49f9123_Source.tar.gz : 3e3ff3a758c8a1ffa71773dff18faff2c792051bb5162758b5f5b8ea59e8e311
license    :
    - CC BY-SA 3.0 # Artistic and Creative Content
    - GPL-2.0 # Source
component  : games.strategy
summary    : FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game
description: |
    FreeOrion is a free, open source, turn-based space empire and galactic conquest (4X) computer game
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(openal)
    - pkgconfig(python-2.7)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - libboost-devel
    - libjpeg-turbo-devel
setup      : |
    %patch -p1 < $pkgfiles/boost-protected-1.61.patch
    %patch -p1 < $pkgfiles/boost-1.61.patch
    %cmake -DCMAKE_INSTALL_LIBDIR=lib%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
